### ISSUE TITLE
Where should the output be?

### ISSUE THREAD

**Issue by jontelm** [evolvingweb/sitediff#115]
```
---
before:
  url: https://www.a.com
  regions:
    - name: title
      selector: h1.title
  output:
    - title
after:
  url: https://beta.b.com
  regions:
    - name: title
      selector: h1.title
  output:
    - title
settings: {}
```

The diff is the fully html page and not only the h1.title as I trying to make it.

Where should output be set?

**Comment by cleaver** [comment]
The `output` key should be at the root level. Just remove the indent from what you have there. Let me know how it works out for you... this is a new feature and it will be great to get some feedback. Thanks!

**Comment by gardon** [comment]
Hi @jontelm the output should be a section in top level, after "settings"

**Comment by jontelm** [comment]
Like this?
```
---
before:
  url: https://www.a.com
  regions:
    - name: title
      selector: h1.title
after:
  url: https://beta.a.com
  regions:
    - name: title
      selector: h1.title
settings: {}
output:
  - title
```

result:
```
Invalid configuration: Unknown configuration key (.../sitediff.yaml): 'output'
```

**Comment by jontelm** [comment]
```
---
before:
  url: https://www.a.com
  regions:
    - name: title
      selector: h1.title
after:
  url: https://beta.a.com
  regions:
    - name: title
      selector: h1.title
output:
  - title
settings: {}
```

Same problem
