### ISSUE TITLE
Merging sanitisation rules from includes

### ISSUE THREAD

**Issue by Mark-Hetherington** [evolvingweb/sitediff#123]
I'd like to merge two sets of sanitisation rules - one "base" set that we apply to all sites, and then a set that is tailored for a site. 

I had hoped to leverage the ["include" functionality](https://github.com/evolvingweb/sitediff#organizing-configuration-files) to put our base rules in a file in a parent directory (this part works), and then add additional rules in the sitediff.yaml. However it appears that the sanitisation: block in the sitediff.yaml overriddes that in the include. I also tried using [YAML anchors](https://yaml.org/spec/1.2/spec.html#&%20anchor//), but the parser reports an "unknown alias".

I'm not sure if I just have the wrong syntax or if this just currently isn't possible?

Example:
testsite/sitediff.yaml:

```
includes:
  - "../base-rules.yaml"
before:
  url: https://beforesite.com
after:
  url: https://aftersite.com
sanitization:
- *base_sanitisation
- title: Strip domain names from absolute URLs
  pattern: https?:\/\/[^\/]+
  substitute: __domain__
  disabled: false
...
```

base-rules.yaml:
```
sanitization: &base_sanitisation
# base sanitisation rules
- title: Strip revision differences
  pattern: \?rev=[^"]+
  disabled: false
```

**Comment by Mark-Hetherington** [comment]
It looks like this actually works in a more current version of sitediff.

**Comment by joeczucha** [comment]
Hi @Mark-Hetherington,

Apologies to resurrect an old thread but I'm having a similar issue:

_shared/cloudflare.yaml

```
sanitization: &cloudflare_sanitization
  - title: Strip protected email hashes
    pattern: '<a.*email-protection#[a-z0-9]+".*<span class="__cf_email__" data-cfemail="[a-z0-9]+">\[emailprotected\]<\/span><\/a>'
    disabled: false
```

sitediff/sitediff.yaml

```
---
before:
  url: https://site.com/
after:
  url: https://site.com/
includes:
  - ../_shared/cloudflare.yaml
sanitization:
  - *cloudflare_sanitization
```

But I’m getting: `Unknown alias: cloudflare_sanitization (Psych::BadAlias)`

Is it working for you? Removing the aliases works fine (so I know the paths are correct) but, as in your case, the sanisation rules overwrite those in the sitediff.yaml file (or are overwritten by subsequent includes). 

Thanks :)
