### ISSUE TITLE
Allow the use of capture groups in substitutions

### ISSUE THREAD

**Issue by LL782** [evolvingweb/sitediff#16]
What I'd like to do is:

```yaml
sanitization:
  - title: Remove trailing whitespace from class values
    pattern: class="([\w\s]+)\s"
    substitute: class="$1"
```

With the desire that this would not be a diff:

```diff
+ class="foo baa "
- class="foo baa"
```

---

_BTW awesome tool! Thank you. I've not written Ruby before but if I can help I'd like to._

**Comment by LL782** [comment]
Any ideas on how to do this?

**Comment by fbarbanson** [comment]
Capture groups are already supported.
```yaml
sanitization:
  - title: Remove trailing whitespace from class values
    pattern: class="([\w\s]+)\s"
    substitute: class="\\1"
```
The way to reference a capture group in Ruby is using a '\\' double backslash syntax, not '$' dollar sign.
