### ISSUE TITLE
Ignore "itok" for image style URIs in Drupal preset

### ISSUE THREAD

**Issue by jigarius** [evolvingweb/sitediff#162]
## The problem

Drupal adds tokens like `?itok=X` to image styles. For example:

```html
<picture>
  <source srcset="/sites/default/files/styles/STYLE/public/slides/2020-10/foo.jpg?itok=VzxcQ5P3" media="(max-width: 1280px)"/>
  <img alt="California, 12' x 7', profil daluminium Noir, verre Clair" src="/sites/default/files/styles/STYLE/public/slides/2020-10/foo.jpg?itok=VzxcQ5P3" width="1240" height="729"/>
</picture>
```

This results in many false positives.

**Comment by jigarius** [comment]
I haven't done much research, but I'm just sharing the quick solution that worked for me.

```yaml
sanitization:
  - title: Ignore itok query parameter from image style URIs
    pattern: \?itok=[^"]+
    substitute: ?itok=__rand__
    selector: source,img
```
