### ISSUE TITLE
Discard <head> elements position

### ISSUE THREAD

**Issue by dhuf** [evolvingweb/sitediff#79]
After a CMS Upgrade the position of the elements is not the same in <head> tag.
Some opengraph entries moved for example.

**Comment by cleaver** [comment]
At the core, Sitediff relies on the [Diffy gem](https://github.com/samg/diffy), which in-turn relies on the native `diff` utility. This means it would take a fundamentally different approach to how we do diffs. I'll post a couple of ideas later for the record.

There's so much going on in the <head> that I just ignore it. We deal with aggregated CSS and JS, so that's going to be different every time. Most CMSs will have cachebusting strategies for assets as well.

To run the diff on a subset of the markup:

```yaml
before:
  url: http://before.example.com
  selector: 'body'

after:
  url: http://after.example.com
  selector: 'body'
```
The `selector` could reference a <div> or other element if you want to be even more specific.
