### ISSUE TITLE
Diff on different URL

### ISSUE THREAD

**Issue by lems3** [evolvingweb/sitediff#88]
When we do a diff on sites on two different URL, the tool shouldn't report the change in base URL as a diff...

Like, if we scan examplea.com and exampleb.com, and my site generate all HREF as absolute URL, for now I get a diff flagged on the HREF, even if the rest of the URL is the same...

Ignoring the whole href with a regex isn't an option since there may be a change in the second part of this url that needs to be flagged...

**Comment by cleaver** [comment]
That's easily addressed with a quick sanitization rule:

```yaml
sanitization:
  - title: Strip domain names from absolute URLs
    pattern: 'http:\/\/[a-zA-Z0-9.:-]+'
    substitute: '__domain__'
```
I don't think that's something we'd set as a default, so I'll close this one. If you have any other questions or concerns, please feel free to reopen.
